apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: central
spec:
  authorization:
    type: rbac
  configOverrides:
    server:
      - confluent.controlcenter.streams.consumer.client.rack=us-central1
      - confluent.controlcenter.streams.replication.factor=-1
      - advertised.listeners=confluent.controlcenter.mydomain.com
  dataVolumeCapacity: 10Gi
  dependencies:
    kafka:
      authentication:
        jaasConfig:
          secretRef: credential
        type: plain
      bootstrapEndpoint: kafka.central.svc.cluster.local:9071,kafka.east.svc.cluster.local:9071,kafka.west.svc.cluster.local:9071
      tls:
        enabled: true
    mds:
      authentication:
        bearer:
          secretRef: c3-mds-client
        type: bearer
      endpoint: https://kafka.central.svc.cluster.local:8090
      tls:
        enabled: true
      tokenKeyPair:
        secretRef: mds-token
    schemaRegistry:
      tls:
        enabled: true
      url: https://schemaregistry.central.svc.cluster.local:8081,https://schemaregistry.east.svc.cluster.local:8081,https://schemaregistry.west.svc.cluster.local:8081
  image:
    application: confluentinc/cp-enterprise-control-center:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: mydomain.com
      prefix: confluent.controlcenter
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: external
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: internal
  replicas: 1
  tls:
    autoGeneratedCerts: true
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   namespace: central
#   name: cp-control-center
#   annotations:
#     alb.ingress.kubernetes.io/load-balancer-name: cp-ingress
#     alb.ingress.kubernetes.io/scheme: internal
#     alb.ingress.kubernetes.io/group.name: citi-poc
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/backend-protocol: HTTP
#     # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
#     # alb.ingress.kubernetes.io/ssl-redirect: '443'
#     # alb.ingress.kubernetes.io/certificate-arn: ""
#     # alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
# spec:
#   ingressClassName: alb
#   rules:
#   - host: confluent.controlcenter.mydomain.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: controlcenter-bootstrap-np
#             port:
#               number: 9021